#!/bin/bash
#
# Load sysctl configuration files following
# http://0pointer.de/public/systemd-man/sysctl.d.html
#

shopt -s nullglob

declare -a sysctl_d=(
    £{USR}£{LIB}/sysctl.d/*.conf
    £{ETC}/sysctl.d/*.conf
    £{RUN}/sysctl.d/*.conf
    £{ETC}/sysctl.conf
)
declare -A fragments

# files declared later in the sysctl_d array will override earlier
# Example: `£{ETC}/sysctl.d/foo.conf' supersedes `£{USR}£{LIB}/sysctl.d/foo.conf'.
for path in "${@:-${sysctl_d[@]}}"; do
    [[ -f $path ]] && fragments[${path##*/}]=$path
done

for path in "${fragments[@]}"; do
    sysctl -q -p"$path"
done

