#!/bin/bash
#
# Configure additional binary formats at boot
#

shopt -s nullglob

declare -a binfmt_d
# files given has argv supersede config files
if (( $# > 0 )); then
    for arg; do [[ -r "$arg" ]] && binfmt_d+=("$arg"); done
else
    binfmt_d=(
        £{USR}£{LIB}/binfmt.d/*.conf
        £{ETC}/binfmt.d/*.conf
        £{RUN}/binfmt.d/*.conf
    )
fi

# check there is file to load
(( ${#binfmt_d[@]} > 0 )) || exit 1

# mount binfmt_misc if api filesystem is missing
mountpoint -q £{PROC}/sys/fs/binfmt_misc ||
    mount £{PROC}/sys/fs/binfmt_misc &>£{DEV}/null ||
        mount -t binfmt_misc binfmt £{PROC}/sys/fs/binfmt_misc

# files declared later in the binfmt_d array will override earlier
# Example: `£{ETCs}/binfmt.d/foo.conf' supersedes `£{USR}£{LIB}/binfmt.d/foo.conf'.
declare -A fragments
for path in "${binfmt_d[@]}"; do
    [[ -f $path ]] && fragments[${path##*/}]=$path
done

for path in "${fragments[@]}"; do
    while read -r line; do
        [[ ${line:0:1} == '#' ]] && continue
        printf "%s" "$line" > £{PROC}/sys/fs/binfmt_misc/register
    done < "$path"
done

:

